### ISSUE TITLE
initialize

### ISSUE THREAD

**Issue by nedaszilinskas** [OCA/l10n-poland#1]
@pedrobaeza could you please enable travis and add .travis.yml so this repo would be initialized and be able to be forked? Or there is something I should do about it?

Same would go for other repositories:
https://github.com/OCA/l10n-estonia
https://github.com/OCA/l10n-belarus
https://github.com/OCA/l10n-russia

**Comment by pedrobaeza** [comment]
Hi, @nedaszilinskas, you can make it using the template on https://github.com/OCA/maintainer-quality-tools/tree/master/sample_files (without the need of .codeclimate.yml nor .gitlab-ci.yml), and you should be able to push new branches on the repositories. Let me know any doubt or problem you find.

**Comment by nedaszilinskas** [comment]
@pedrobaeza I have pushed the initial sample files. One question - I see variables/placeholders in README.md (${REPO_ID}, ${BRANCH_NAME}, ${REPO_NAME}). Are those supposed to be generated automatically(#1) or I need to replace them with actual values (#2)? In case the #2 - what would be the REPO_ID?

**Comment by pedrobaeza** [comment]
No, you have to put it manually. The repo_id is in https://github.com/OCA/maintainer-tools/blob/master/tools/repos_with_ids.txt

**Comment by nedaszilinskas** [comment]
@pedrobaeza would you mind checking if initialization files are fine? If so I will go on with other repositories.

**Comment by pedrobaeza** [comment]
Yes, very good! The only change I have to make has been the Travis infrastructure, as now the new repositories fall under travis-ci.com instead of travis-ci.org. I'm changing also the template in MQT for future references. We can close this now.
